services:
  mtgjson:
    image: gitea.prod02.asgard-server.net/odin/mtgjson-api:dev-latest
    container_name: dev-mtgjson-api
    volumes:
      - "/home/szaluk/.config/mtgjson-api:/root/.config/mtgjson-api"
    ports:
      - "8080:8080"
    restart: unless-stopped
