name: Development
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Go-Lang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache: false

      - name: Install dependencies
        run: |
          go get .

      - name: Run unit tests
        run: go test -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.REGISTRY_USER}}
          password: ${{secrets.REGISTRY_TOKEN}}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.REGISTRY_TAG}}/mtgjson-api:dev-latest, ${{secrets.REGISTRY_TAG}}/mtgjson-api:${{env.GITHUB_SHA}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.REGISTRY_USER}}
          password: ${{secrets.REGISTRY_TOKEN}}

      - name: Stop existing containers
        run: docker compose -p dev01-deploy down

      - name: Pull dev-latest
        run: docker compose -f docker/docker-compose.yaml pull

      - name: Deploy
        run: docker compose -p dev01-deploy -f docker/docker-compose.yaml up -d
