{
	"mongo.ip":"127.0.0.1",
	"mongo.port":27017,
	"mongo.user":"admin",
	"mongo.pass":"admin",
	"api.namespaces":["card", "deck", "set", "auth", "user"],
	"auth0.audience":"https://auth0.audience.here.com",
	"auth0.domain":"",
	"auth0.client_id":"",
	"auth0.client_secret":"",
	"auth0.scope":"read:user write:user read:profile read:card write:card write:system-card read:set write:set write:system-set read:deck write:deck write:system-deck read:health read:metrics read:user-card read:user-set read:user-deck write:user-card write:user-set write:user-deck reset:password email openid profile",
	"log.path:"/var/log/mtgjson-api"
}
